name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        restic-version: ['0.10.0', '0.11.0', '0.12.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (${{ matrix.restic-version }})
        if: ${{ matrix.restic-version != '0.12.0' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RESTIC_VERSION=${{ matrix.restic-version }}
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/amd64,linux/ppc64le
          push: true
          tags: rossimarco/restic:${{ matrix.restic-version }}
      - name: Build and push (latest)
        if: ${{ matrix.restic-version == '0.12.0' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RESTIC_VERSION=${{ matrix.restic-version }}
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/amd64,linux/ppc64le
          push: true
          tags: rossimarco/restic:${{ matrix.restic-version }},rossimarco/restic:latest
